import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans } from "next/font/google";
import { Lato } from "next/font/google";

const DMSansFont = DM_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-dm-sans",
});

const LatoFont = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Developers' Guild",
  description: "Generated by RAMPP",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-white text-black ${DMSansFont.variable} ${LatoFont.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
